language: php

php:
    - 5.3
    - 5.5
    - 5.6
    - hhvm

before_script:
    - composer self-update
    - composer install --prefer-source -v --dev

script: phpunit

matrix:
    allow_failures:
    - php: 5.6
    - php: hhvm

